export {default as Login} from './login/cnx.page'

export {default as MainLayout} from './layout/layout.page'

export {default as Home} from './home/home.page'

export {default as Categorie} from './categorie/categorie.page'

export {default as Footer} from './footer/footer'
export {default as Produits} from'./produits/produit.page'
export {default as FormulaireProduits} from'./formulaireproduits/Produits.formulaire'
export {default as CreatePersonnels} from'./personnelles/createPersonnel.page'
export {default as CreateProduits} from'./produits/createProduits.page'
export {default as CreateCommande} from'./commande/createCommande.page'
export {default as Commande} from'./commande/commande.page'
export {default as Fournisseurs} from'./Fournisseurs/fournisseur.page'
export {default as CreateFournisseurs} from'./Fournisseurs/createFourniseur.page'
export {default as EditerProduit} from'./produits/editerProduits.page'
export {default as EditerCategorie} from'./categorie/editerCategorieFormulaire'
export {default as CreateCategories} from'./categorie/createCategories.pages'
export {default as EditerPersonnel} from'./personnelles/editerPersonnel.page'
export {default as  Persons} from'./personnelles/personnels.page'
export {default as EditerCommande} from'./commande/editeCommande.page'
export {default as Clien} from'./clientes/client.page'
export {default as CreateClins} from'./clientes/ajouterClient.page'
export {default as  EditerClin} from'./clientes/editerClient.page'
export {default as  Enregistrements} from'./enregistrement/Enregistre.page'
